# Generated by Django 3.1.1 on 2020-12-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='назва тренування')),
                ('photo_url', models.URLField(max_length=1000, verbose_name='посилання на фото тренування')),
                ('regione', models.CharField(max_length=50, verbose_name='територія де відбуватиметься тренування')),
                ('difficulty', models.PositiveSmallIntegerField(verbose_name='складність')),
             ],
            options={
                'verbose_name': 'тренування',
                'verbose_name_plural': 'тренування',
            },
        ),
        migrations.CreateModel(
            name='Training_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата створення події')),
                ('start_date', models.DateTimeField(verbose_name='запланована дата початку тренування')),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainings.training')),
            ],
            options={
                'verbose_name': 'Подія тренування',
                'verbose_name_plural': 'Події тренування',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='нік')),
                ('password', models.CharField(max_length=40, verbose_name='пароль')),
                ('name', models.CharField(max_length=30, verbose_name='ім`я')),
                ('age', models.PositiveSmallIntegerField(verbose_name='вік')),
                ('phone', models.CharField(max_length=30, verbose_name='мобільний номер')),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
                ('condition', models.PositiveSmallIntegerField(verbose_name='фізичний стан')),
                ('training_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.training_event')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
            },
        ),
    ]
